name: Designer Shauny
favicon: null
layout_spectrum: 1
typography_spectrum: 0.61144
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c9d1c6'
    - '#91948b'
    - '#1a1413'
    - '#563127'
    - '#925647'
  brandStrength: 0.4375
  lightness: 0.3125
  saturation: 0.625
  rhythmicContrast: 0.06580944103188813
purpose: []
